spring:
  application:
    name: todo-application-be
  datasource:
    url: ENC(h8R8XO4y4mlyzdrshnL+8e8YNl4WumNh245vNPs1mPkeQDe9p5HlC5SklUUrOLGf/534ccMTepAiAKxwQ/yv3poSDGwVhPYfFLil2vCJLdD2JBpYsUEmkbMTrlzLaLjINEnj+ZI+DWV70nI/4gRUkQ==)
    username: ENC(qZQUVLg2zqcVT0pwkhh7UP4H4tys+Bf89EZALfW6MgEJAQOdXKbuoCqHiM6dYc2L)
    password: ENC(fzfYv87OWEziKZAXbInb/w3LfqVsBLMQxeuBMR4sk0RqHGixgb9eiQVKyV+wi1Fp)
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 30000
      maxLifeTime: 600000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ENC(MvMOPRbcirdJZHm9+Gb7rXmWzzf2UE2cnQ9FTqNbKIicMy/TUlvZ7h0x/UvhM0FG+Oevu2N7sFTW0/tEerHoQYJW8noN8tI5qMDn5rDDxt6F3YTKcjTSbTp3+w2H8Knq)
          jwk-set-uri: ENC(faNU/Tb1RiPShe5ixTauqOGJYny3ycc3bCMRgH0wFbmmzIdhNTkWWSO6yA9lLdy1FDLSUPuBWiF6NetmXRyEc6+67bTPDykCrW5WDQoJv+ZvP34eZFRg/GS7awbA+LU3RmSMaBu1C6QHIBdE8sGh4/iy56TCaSMiBVHqN2QJnxM=)

springdoc:
  default-produces-media-type: application/json

cognito:
  client-id: ENC(qe1RRABknyyqt63iZwYPskWu6HBjvDfMt+mI5Z0/LECelmtvpBU/N8NFED09YcFtus/J4HmLMaXl+UuSoUuK9Q==)
  client-secret: ENC(YM4znh3oAsO3W22F/NcW0tTnsjWyqZJS8kW03XQ4eAEu8aVzX8QRrK6X26qYeaAMtSloN6qPxDimqmLCGrn5g3PfMoXbfocswPEHyaPChw1U9TsC9H4OGxnkW3VwsTcX)
  domain: ENC(y6JH6ypGYH5o4NbwKPrW7tbS4Oa201Bm0q8Yf0dPWf1ZSYLkuJFtzi6b2tfKiTYBX5Ky4/T8Nj1B8EZPf6s4wkIwRgi83qA8ol70Cn+K3ys=)


jasypt:
  encryptor:
    algorithm: PBEWithHMACSHA512AndAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64